# Generated by Django 5.1.3 on 2024-12-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chatmodel_remove_message_group_chat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ['timestamp']},
        ),
    ]
